# Describe Cloud Benefits

::: {.callout-note}
## Source
<https://learn.microsoft.com/en-gb/training/modules/describe-benefits-use-cloud-services/>
:::


## High Availability and Scalability

Availability can be defined in terms of uptime, when the sever is available for
    use, and downtime, not available for use due to maintenance, repairs or
    upgrades.
Many obligations from providers vary between 99% and 99.9% availability,
    depending on business requirements.
Such agreements are laid out in service level agreements (SLAs).
  
Scalability is the ability to handle surge demand, where traffic will peak for
    a short time and reduce back to background level after some time.
This can be done in two ways

1. **Vertical**: improving current resources such as CPU compute or RAM,

1. **Horizontal**: including more machines to handle more compute.

Horizontal scaling is made easier with on-demand cloud computing.


## Reliability and Predictability

Reliability, defined as the ability to recover from failures, is a requirement
    for many frameworks.
Decentralised computing offered by cloud services allows for higher
    resilience from regional catastrophic events.

When using an on-demand service, predictable performance and costs are heavily
    desired.
By deploying to the cloud, with solutions including autoscaling and monitoring,
    one has a better idea for performance that may impact user experience.
Similarly, cost is more predictable thanks to analytics and consistent
    environments (no paying for a Windows upgrade or stray process).


## Security and Governance

In the age of data, governance and security of who can access data is
    imperative.
Cloud computing enables system administrators to update several machines at
    once through use of policy.
Such rules can be fine-tuned to adhere to regulatory requirements and
    standards including international standards (ISOs).

Furthermore, as these services are procured over the internet, network
    security from distributed denial of service (DDoS) or man in the middle
    attacks *should* be controlled in advance.


## Manageability

Management of the cloud includes scaling, deploying, health monitoring and
    setting up alerts for some number of resources.
This can be done using a

1. web portal,

1. command line interface (including Powershell),

1. API.

