project:
  type: book

book:
  title: "Python Basics"
  author: "Josh Cowley"
  search: true
  repo-url: https://github.com/nclJoshCowley/jcnotes/python_basics
  chapters:
    - index.qmd
    - chapters/01_basics.qmd
    - chapters/references.qmd

bibliography: python_basics.bib

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: pdflatex
    documentclass: scrreprt
