project:
  type: book

book:
  title: "Statistical Machine Learning"
  subtitle: "APTS 2021, Oxford"
  author: "Josh Cowley"
  search: true
  repo-url: https://github.com/nclJoshCowley/jcnotes/Statistical-ML
  repo-actions: [source]
  chapters:
    - index.qmd
    - chapters/02-intro.qmd
    - chapters/03-supervised-learning.qmd
    - chapters/04-local-methods.qmd
    - chapters/05-error-estimation.qmd
    - chapters/06-trees-forests.qmd
    - chapters/07-model-assessment.qmd
    - chapters/08-ml-pipelines.qmd
    - chapters/references.qmd

bibliography: Statisical-ML.bib

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: pdflatex
    documentclass: scrreprt
    include-in-header:
      - header.tex
